kloia/platform-modules

aws-vpc/README.md, aws-vpc/main.tf, aws-vpc/modules/vpc-endpoints/README.md, aws-vpc/outputs.tf, aws-vpc/variables.tf
=> refactor vpc module for dynamic subnet creation

aws-ecr/main.tf, aws-ecr/variables.tf
We have converted the values of ecr_repo_names from strings to a list
=> Change value type (ecr_repo_names).

aws-rds-aurora/main.tf
update data aws_subnet_ids to aws_subnets in rds module.
=> update data aws_subnet_ids to aws_subnets for rds

aws-mongodbatlas-cluster/main.tf, aws-mongodbatlas-cluster/outputs.tf, aws-vpc-peering-accepter/README.md, aws-vpc-peering-accepter/outputs.tf, aws-vpc-peering-accepter/routes.tf, aws-vpc-peering-accepter/variables.tf
changes: 
1 - add multiple peering outputs to mongo atlas
2 - add multiple peer accepter with multiple route propagation. 
3 - fix bugs in mongo atlas module
=> Fix mongoatlas update peer module

aws-mongodbatlas-cluster/outputs.tf
fix mongo atlas cluster output
=> fix mongo atlas cluster output

aws-mongodbatlas-access/main.tf, aws-mongodbatlas-access/outputs.tf, aws-mongodbatlas-access/variables.tf, aws-mongodbatlas-auth/aws-roles.tf, aws-mongodbatlas-auth/main.tf, aws-mongodbatlas-auth/variables.tf, aws-mongodbatlas-cluster/main.tf, aws-mongodbatlas-cluster/outputs.tf
changes: 
1 - add encyption at rest 
2- update mongoatlas cluster output
3 - fix bugs
=> update  mongoatlas modules fo encryption at rest support

aws-eks-rancher-importer/README.md, aws-eks-rancher-importer/main.tf, aws-eks-rancher-importer/variables.tf, aws-eks-rancher-importer/versions.tf, aws-eks-rancher-joiner/README.md, aws-eks-rancher-joiner/main.tf, aws-eks-rancher-joiner/variables.tf, aws-eks-rancher-joiner/versions.tf
Two modules for importing/joining existing EKS clusters to Rancher
=> feat(rancher): add rancher-joiner and rancher-importer modules

aws-cloudwatch/modules/log-subscription-filter/README.md, aws-cloudwatch/modules/log-subscription-filter/main.tf, aws-cloudwatch/modules/log-subscription-filter/outputs.tf, aws-cloudwatch/modules/log-subscription-filter/variables.tf, aws-cloudwatch/modules/log-subscription-filter/versions.tf
changes:
- add cloudwatch subscription filter resource.
=> add cloudwatch-log subscirption filter

aws-eks-rancher-importer/README.md, aws-eks-rancher-importer/main.tf, aws-eks-rancher-importer/variables.tf, aws-eks-rancher-joiner/README.md, aws-eks-rancher-joiner/main.tf, aws-eks-rancher-joiner/variables.tf
- fix(rancher): rancher agent registration and optional cluster name
- docs(rancher): terraform import usage, rancher_cluster_name option
=> Fix Rancher import and join modules

aws-cloudwatch/modules/log-group/README.md, aws-cloudwatch/modules/log-group/main.tf, aws-cloudwatch/modules/log-group/variables.tf, aws-elasticsearch/main.tf, aws-elasticsearch/outputs.tf, aws-ssm-parameter-store/README.md, aws-ssm-parameter-store/main.tf, aws-ssm-parameter-store/outputs.tf, aws-ssm-parameter-store/variables.tf
changes: 
- add aws_cloudwatch_log_resource_policy to cloudwatch log group access.
- add random_password to opensearch for internal user random password creatation
- add cross account read support for ssm parameter store
=> update and add features to operate opensearch

aws-transit-gateway/README.md, aws-transit-gateway/main.tf, aws-transit-gateway/variables.tf
changes:
- add multi-env route-table support
=> Add transit gw

aws-vpc/outputs.tf
changes:
- add all route table id output value
=> update vpc route table output

aws-eks-addons/main.tf, aws-eks-addons/variables.tf
changes:
- add aws loadbalancer controller chart version variable
- add karpenter chart version variable
- fix rancher_hostname variable default values
=> add karpenter & aws lb controller version

aws-elasticsearch/main.tf, aws-elasticsearch/variables.tf
changes: 
- update random password criteria
- add saml idp support to elasticsearch module
=> add saml auth support to elasticsearch

aws-lambda/main.tf, aws-lambda/variables.tf
changes:
- add subnet selection variable for lambda functions.
=> add lambda subnet select variable

README.md, aws-cognito-user-pool/CHANGELOG.md, aws-cognito-user-pool/LICENSE, aws-cognito-user-pool/README.md, aws-cognito-user-pool/client.tf, aws-cognito-user-pool/domain.tf, aws-cognito-user-pool/examples/complete/README.md, aws-cognito-user-pool/examples/complete/main.tf, aws-cognito-user-pool/examples/complete/provider.tf, aws-cognito-user-pool/examples/complete/variables.tf, aws-cognito-user-pool/examples/simple/README.md, aws-cognito-user-pool/examples/simple/main.tf, aws-cognito-user-pool/examples/simple/provider.tf, aws-cognito-user-pool/examples/simple/variables.tf, aws-cognito-user-pool/examples/simple_extended/README.md, aws-cognito-user-pool/examples/simple_extended/main.tf, aws-cognito-user-pool/examples/simple_extended/provider.tf, aws-cognito-user-pool/examples/simple_extended/variables.tf, aws-cognito-user-pool/identity-provider.tf, aws-cognito-user-pool/main.tf, aws-cognito-user-pool/outputs.tf, aws-cognito-user-pool/resource-server.tf, aws-cognito-user-pool/user-group.tf, aws-cognito-user-pool/variables.tf, aws-cognito-user-pool/versions.tf, aws-iam/modules/iam-assumable-role/main.tf
changes:
- add aws congito module
- fix aws iam policy document for iam assumable role
=> add cognito module and fix iam-assumable-role

aws-lambda/main.tf, aws-lambda/variables.tf
changes:
- fix lambda vpc settings for subnet selection
=> fix lambda subnet variable

aws-route53-health-check-main/main.tf, aws-route53-health-check-main/outputs.tf, aws-route53-health-check-main/variables.tf
- Add route53 healthcheck with tcp type
=> Update route53 healthcheck

aws-transit-gateway/main.tf, aws-transit-gateway/variables.tf
changes: 
- add transit gateway peering
- fix cross account transit gatewat setup
=> add tgw peering & fix cross account setup

modules/aws-rds-aurora/sql-server.tf, modules/aws-rds-aurora/variables.tf
BREAKING CHANGE: needs apply method to be supplied for all parameter groups
=> feat(rds-aurora)!: add apply method
